# Non-linear regression | Levenberg Marquardt Algorithm

Author: Rudransh Jaiswal

In [3]:
import numpy as np
import math
pi=np.pi
e=np.e

## Levenberg-Marquardt Algorithm
 It is known that $ \hat y = f(\bar A,x);\quad A=[a,b,c..]$
 
 Given some values of x and y, we have to find estimate of $\bar A$, but the equation cannot be linearised and hence the usual least square (min. L2-norm) cannot be applied.
 
 We solve it iteratively:
 1. Initialise $\bar A$ to some constant.
 2. Calculate Jacobian
 $ Z = \begin{bmatrix}
\frac{\partial f}{\partial a}\Bigr\rvert_{x1} & \frac{\partial f}{\partial b}\Bigr\rvert_{x1} & \frac{\partial f}{\partial c}\Bigr\rvert_{x1}\\
\frac{\partial f}{\partial a}\Bigr\rvert_{x2} & \frac{\partial f}{\partial b}\Bigr\rvert_{x2} & \frac{\partial f}{\partial c}\Bigr\rvert_{x2}\\
. & . & .
\end{bmatrix} $
 
 3. Solve $( Z^TZ + \lambda $diag$(Z^TZ))\Delta A = Z^T \Delta Y; \quad \Delta Y = Y-\hat Y$
 4. Update $A=A+\Delta A$
 5. Iterate until convergence

In [4]:
# X : independent variable
# Y : dependent variable
# A: design variable
# y_pred: function: returns Y^ given some A
# J: function to calculate Jacobian Z
def LevenMarq(A,X,Y,y_pred,J,lamb,n_iters):
    for n in range(n_iters):
        print('\n# ITERATION:',n+1)
        dY=[]
        Z=[]
        for i in range(len(T)):
            dY.append(Y[i]-y_pred(A,X[i]))
            Z.append(J(A,X[i])) # change Z accordingly include dfdc if required
        dY=np.array(dY)
        Z=np.array(Z)
        Qcurr=np.matmul(Z.T,Z)
        Q=Qcurr + lamb*np.diag(np.diag(Qcurr)) ### here is the change
        det=np.linalg.det(Q)
        Qinv=np.linalg.inv(Q)
        R=np.matmul(Z.T,dY)
        dA=np.matmul(Qinv,R)
        print('Y_pred:',Y-dY)
        print('dY:',dY)
        print('Z:\n',Z)
        print('Z.T Z:\n',Qcurr)
        print('Z.T Z +lamb*diag():\n',Q)
        print('det::',det)
        print('inv(Z.T Z +lamb*diag()):\n',Qinv)
        print('Z.T dY:',R)
        print('dA:',dA)
        Anew=A+dA
        print('Anew:',Anew)
        rel_err=[]
        for j in range(len(A)):
            rel_err.append((Anew[j]-A[j])/A[j])
        print('errors:',rel_err)
        A=Anew

- Given a solution to a equation in heat transfer

$\hat y = a*erf(b/t); \quad erf: error function$

Solving it using Levenberg-Marquardt Algorithm

In [5]:
def y_pred(A,t): return A[0]*math.erf(A[1]/math.sqrt(t))
def dfda(A,t): return math.erf(A[1]/math.sqrt(t))
def dfdb(A,t): return (2*A[0]/((pi*t)**0.5))*(pow(e,-A[1]*A[1]/t))
def J1(A,t): return [dfda(A,t),dfdb(A,t)]
T=np.array([60,81,99,118,142,157])
Y=np.array([45.92,41.61 ,37.87, 35.10, 32.69 ,31.29])
A0=np.array([50,6])
lamb=0.5
LevenMarq(A0,T,Y,y_pred,J1,lamb,2)


# ITERATION: 1
Y_pred: [36.33391609 32.71107069 30.31156827 28.26379996 26.17889736 25.08602053]
dY: [9.58608391 8.89892931 7.55843173 6.83620004 6.51110264 6.20397947]
Z:
 [[0.72667832 3.99735528]
 [0.65422141 4.0194144 ]
 [0.60623137 3.94168759]
 [0.565276   3.82813671]
 [0.52357795 3.67432921]
 [0.50172041 3.58007223]]
Z.T Z:
 [[ 2.1689777  13.80789991]
 [13.80789991 88.64368541]]
Z.T Z +lamb*diag():
 [[  3.25346655  13.80789991]
 [ 13.80789991 132.96552811]]
det:: 241.9407986766073
inv(Z.T Z +lamb*diag()):
 [[ 0.54957878 -0.0570714 ]
 [-0.0570714   0.01344737]]
Z.T dY: [ 27.75610056 176.18498187]
dA: [5.19904035 0.7851445 ]
Anew: [55.19904035  6.7851445 ]
errors: [0.10398080700027364, 0.13085741670189233]

# ITERATION: 2
Y_pred: [43.30792778 39.39328601 36.71585137 34.38641402 31.97811276 30.70248104]
dY: [2.61207222 2.21671399 1.15414863 0.71358598 0.71188724 0.58751896]
Z:
 [[0.78457755 3.73315017]
 [0.71365889 3.92015253]
 [0.6651538  3.93195084]
 [0.62295311 3.88153765]
 [0.57