# Non-linear regression | Levenberg Algorithm

Author: Rudransh Jaiswal

In [1]:
import numpy as np
import math
pi=np.pi
e=np.e

## Levenberg Algorithm
 It is known that $ \hat y = f(\bar A,x);\quad A=[a,b,c..]$
 
 Given some values of x and y, we have to find estimate of $\bar A$, but the equation cannot be linearised and hence the usual least square (min. L2-norm) cannot be applied.
 
 We solve it iteratively:
 1. Initialise $\bar A$ to some constant.
 2. Calculate Jacobian
 $ Z = \begin{bmatrix}
\frac{\partial f}{\partial a}\Bigr\rvert_{x1} & \frac{\partial f}{\partial b}\Bigr\rvert_{x1} & \frac{\partial f}{\partial c}\Bigr\rvert_{x1}\\
\frac{\partial f}{\partial a}\Bigr\rvert_{x2} & \frac{\partial f}{\partial b}\Bigr\rvert_{x2} & \frac{\partial f}{\partial c}\Bigr\rvert_{x2}\\
. & . & .
\end{bmatrix} $
 
 3. Solve $( Z^TZ + \lambda I)\Delta A = Z^T \Delta Y; \quad \Delta Y = Y-\hat Y$
 4. Update $A=A+\Delta A$
 5. Iterate until convergence

In [2]:
# X : independent variable
# Y : dependent variable
# A: design variable
# y_pred: function: returns Y^ given some A
# J: function to calculate Jacobian Z


def Levenberg(A,X,Y,y_pred,J,lamb,n_iters):
    for n in range(n_iters):
        print('\n# ITERATION:',n+1)
        dY=[]
        Z=[]
        for i in range(len(X)):
            dY.append(Y[i]-y_pred(A,X[i]))
            Z.append(J(A,X[i])) # change Z accordingly include dfdc if required
        dY=np.array(dY)
        Z=np.array(Z)
        Qcurr=np.matmul(Z.T,Z)
        Q=Qcurr + lamb*np.identity(len(Qcurr)) ### here is the change
        det=np.linalg.det(Q)
        Qinv=np.linalg.inv(Q)
        R=np.matmul(Z.T,dY)
        dA=np.matmul(Qinv,R)
        print('Y_pred:',Y-dY)
        print('dY:',dY)
        print('Z:\n',Z)
        print('Z.T Z:\n',Qcurr)
        print('Z.T Z + lamb*I :\n',Q)
        print('det::',det)
        print('inv(Z.T Z + lamb*I):\n',Qinv)
        print('Z.T dY:',R)
        print('dA:',dA)
        Anew=A+dA
        print('Anew:',Anew)
        rel_err=[]
        for j in range(len(A)):
            rel_err.append((Anew[j]-A[j])/A[j])
        print('errors:',rel_err)
        A=Anew

- Given a solution to a equation in heat transfer

$\hat y = a*erf(b/t); \quad erf: error function$

Solving it using Levenberg Algorithm

In [3]:
        
def y_pred(A,t): return A[0]*math.erf(A[1]/math.sqrt(t))
def dfda(A,t): return math.erf(A[1]/math.sqrt(t))
def dfdb(A,t): return (2*A[0]/((pi*t)**0.5))*(pow(e,-A[1]*A[1]/t))
def J1(A,t): return [dfda(A,t),dfdb(A,t)]

T=np.array([60,81,99,118,142,157])
Y=np.array([45.92,41.61 ,37.87, 35.10, 32.69 ,31.29])
A0=np.array([50,6])
lamb=0.5
Levenberg(A0,T,Y,y_pred,J1,lamb,2)


# ITERATION: 1
Y_pred: [36.33391609 32.71107069 30.31156827 28.26379996 26.17889736 25.08602053]
dY: [9.58608391 8.89892931 7.55843173 6.83620004 6.51110264 6.20397947]
Z:
 [[0.72667832 3.99735528]
 [0.65422141 4.0194144 ]
 [0.60623137 3.94168759]
 [0.565276   3.82813671]
 [0.52357795 3.67432921]
 [0.50172041 3.58007223]]
Z.T Z:
 [[ 2.1689777  13.80789991]
 [13.80789991 88.64368541]]
Z.T Z + lamb*I :
 [[ 2.6689777  13.80789991]
 [13.80789991 89.14368541]]
det:: 47.26440884307247
inv(Z.T Z + lamb*I):
 [[ 1.88606369 -0.2921416 ]
 [-0.2921416   0.05646908]]
Z.T dY: [ 27.75610056 176.18498187]
dA: [0.87881141 1.84029235]
Anew: [50.87881141  7.84029235]
errors: [0.01757622821303286, 0.306715390874538]

# ITERATION: 2
Y_pred: [43.12968423 39.78949958 37.38980984 35.23929913 32.96300789 31.73784567]
dY: [ 2.79031577  1.82050042  0.48019016 -0.13929913 -0.27300789 -0.44784567]
Z:
 [[0.84769441 2.66060475]
 [0.7820446  2.98653262]
 [0.73487978 3.1011032 ]
 [0.69261247 3.13915206]
 [0.64787299 