# Non-linear regression | Gauss Newton Algorithm

Author: Rudransh Jaiswal

In [1]:
import numpy as np
import math
pi=np.pi
e=np.e

## Gauss Newton Algorithm
 It is known that $ \hat y = f(\bar A,x);\quad A=[a,b,c..]$
 
 Given some values of x and y, we have to find estimate of $\bar A$, but the equation cannot be linearised and hence the usual least square (min. L2-norm) cannot be applied.
 
 We solve it iteratively:
 1. Initialise $\bar A$ to some constant.
 2. Calculate Jacobian
 $ Z = \begin{bmatrix}
\frac{\partial f}{\partial a}\Bigr\rvert_{x1} & \frac{\partial f}{\partial b}\Bigr\rvert_{x1} & \frac{\partial f}{\partial c}\Bigr\rvert_{x1}\\
\frac{\partial f}{\partial a}\Bigr\rvert_{x2} & \frac{\partial f}{\partial b}\Bigr\rvert_{x2} & \frac{\partial f}{\partial c}\Bigr\rvert_{x2}\\
. & . & .
\end{bmatrix} $
 
 3. Solve $ Z^TZ \Delta A = Z^T \Delta Y; \quad \Delta Y = Y-\hat Y$
 4. Update $A=A+\Delta A$
 5. Iterate until convergence

In [2]:
# X : independent variable
# Y : dependent variable
# A: design variable
# y_pred: function: returns Y^ given some A
# J: function to calculate Jacobian Z


def GNA(A,X,Y,y_pred,J,n_iters):
    for n in range(n_iters):
        print('\n# ITERATION:',n+1)
        dY=[]
        Z=[]
        for i in range(len(X)):
            dY.append(Y[i]-y_pred(A,X[i]))
            Z.append(J(A,X[i])) 
        
        dY=np.array(dY)
        Z=np.array(Z)
        Q=np.matmul(Z.T,Z)
        det=np.linalg.det(Q)
        Qinv=np.linalg.inv(Q)
        R=np.matmul(Z.T,dY)
        dA=np.matmul(Qinv,R)
        print('Y_pred:',Y-dY)
        print('dY:',dY)
        print('Z:\n',Z)
        print('Z.T Z:\n',Q)
        print('det::',det)
        print('inv(Z.T Z):\n',Qinv)
        print('Z.T dY:',R)
        print('dA:',dA)
        Anew=A+dA
        print('Anew:',Anew)
        rel_err=[]
        for j in range(len(A)):
            rel_err.append((Anew[j]-A[j])/A[j])
        print('errors:',rel_err)
        A=Anew

- Given a solution to a equation in heat transfer

$\hat y = a*erf(b/t); \quad erf: error function$

Solving it using Gauss-Newton Algorithm

In [3]:
def y_pred(A,t): return A[0]*math.erf(A[1]/math.sqrt(t))
def dfda(A,t): return math.erf(A[1]/math.sqrt(t))
def dfdb(A,t): return (2*A[0]/((pi*t)**0.5))*(pow(e,-A[1]*A[1]/t))
def J01(A,t): return [dfda(A,t),dfdb(A,t)]

X=np.array([60,81,99,118,142,157])
Y=np.array([45.92,41.61 ,37.87, 35.10, 32.69 ,31.29])
A0=np.array([50,6])

GNA(A0,X,Y,y_pred,J01,n_iters=2)


# ITERATION: 1
Y_pred: [36.33391609 32.71107069 30.31156827 28.26379996 26.17889736 25.08602053]
dY: [9.58608391 8.89892931 7.55843173 6.83620004 6.51110264 6.20397947]
Z:
 [[0.72667832 3.99735528]
 [0.65422141 4.0194144 ]
 [0.60623137 3.94168759]
 [0.565276   3.82813671]
 [0.52357795 3.67432921]
 [0.50172041 3.58007223]]
Z.T Z:
 [[ 2.1689777  13.80789991]
 [13.80789991 88.64368541]]
det:: 1.6080772892658362
inv(Z.T Z):
 [[55.12402047 -8.58658971]
 [-8.58658971  1.3488019 ]]
Z.T dY: [ 27.75610056 176.18498187]
dA: [17.19970285 -0.69160926]
Anew: [67.19970285  5.30839074]
errors: [0.34399405691591256, -0.115268209571506]

# ITERATION: 2
Y_pred: [44.8586359  40.03718197 36.92301373 34.304997   31.6711476  30.30170552]
dY: [1.0613641  1.57281803 0.94698627 0.795003   1.0188524  0.98829448]
Z:
 [[0.66754218 6.12040688]
 [0.59579403 5.94968005]
 [0.54945204 5.73308999]
 [0.51049328 5.49755563]
 [0.47129892 5.21789355]
 [0.45092023 5.05735695]]
Z.T Z:
 [[  1.78853575  18.32658899]
 [ 18.326