In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

e=np.e
pi=np.pi
inf=math.inf

In [12]:
def pivot(Z,b,i0,j0):
    p=Z[i0][j0]
    for i in range(len(Z)):
        if i==i0: continue
        else:
            q=Z[i][j0]
            Z[i]=p*Z[i]-q*Z[i0]
            b[i]=p*b[i]-q*b[i0]
    return Z,b

def simplex(Z,b):
    n_iter=0
    print('iteration:',n_iter)
    print('Z=',Z,sep='')
    print('b=',b)
    while any(Z[-1]<0):
        n_iter+=1
        print('iteration:',n_iter)
        j0=np.argmin(Z[[-1]])
        print('s=',j0+1)
        i_arr=[]
        for i in range(len(Z)):
            if Z[i][j0]>0: i_arr.append(b[i]/Z[i][j0])
            else: i_arr.append(np.Inf)
        i0=np.argmin(i_arr)
        print('r=',i0+1)
        Z,b=pivot(Z,b,i0,j0)
        print('Z=',Z,sep='')
        print('b=',b)
    return Z,b

In [13]:
Z=np.array([[4.8,2.5,1,0,0,0],[1,0,0,1,0,0],[0,1,0,0,1,0],[4.6,2.3,0,0,0,1],[-12000,-3000,0,0,0,0]])
b=np.array([6800,500,5000,7200,1j])
Zf,bf=simplex(Z,b)

iteration: 0
Z=[[ 4.8e+00  2.5e+00  1.0e+00  0.0e+00  0.0e+00  0.0e+00]
 [ 1.0e+00  0.0e+00  0.0e+00  1.0e+00  0.0e+00  0.0e+00]
 [ 0.0e+00  1.0e+00  0.0e+00  0.0e+00  1.0e+00  0.0e+00]
 [ 4.6e+00  2.3e+00  0.0e+00  0.0e+00  0.0e+00  1.0e+00]
 [-1.2e+04 -3.0e+03  0.0e+00  0.0e+00  0.0e+00  0.0e+00]]
b= [6800.+0.j  500.+0.j 5000.+0.j 7200.+0.j    0.+1.j]
iteration: 1
s= 1
r= 2
Z=[[ 0.0e+00  2.5e+00  1.0e+00 -4.8e+00  0.0e+00  0.0e+00]
 [ 1.0e+00  0.0e+00  0.0e+00  1.0e+00  0.0e+00  0.0e+00]
 [ 0.0e+00  1.0e+00  0.0e+00  0.0e+00  1.0e+00  0.0e+00]
 [ 0.0e+00  2.3e+00  0.0e+00 -4.6e+00  0.0e+00  1.0e+00]
 [ 0.0e+00 -3.0e+03  0.0e+00  1.2e+04  0.0e+00  0.0e+00]]
b= [4.4e+03+0.j 5.0e+02+0.j 5.0e+03+0.j 4.9e+03+0.j 6.0e+06+1.j]
iteration: 2
s= 2
r= 1
Z=[[ 0.00e+00  2.50e+00  1.00e+00 -4.80e+00  0.00e+00  0.00e+00]
 [ 2.50e+00  0.00e+00  0.00e+00  2.50e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00 -1.00e+00  4.80e+00  2.50e+00  0.00e+00]
 [ 0.00e+00  0.00e+00 -2.30e+00 -4.60e-01  0.00e+00  2